# Generated by Django 2.1.1 on 2018-09-19 08:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name_plural': 'категории',
                'verbose_name': 'категория дизайна',
            },
        ),
        migrations.CreateModel(
            name='DesignProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='design_products/main', verbose_name='Основное изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_products.DesignCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'дизайн',
                'verbose_name': 'дизайн-работы',
            },
        ),
        migrations.CreateModel(
            name='DesignProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='design_products/detail', verbose_name='Дополнительное изображение')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('thumbnail', models.ImageField(upload_to='design_products/thumbnails', verbose_name='Дополнительное изображение')),
                ('design_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_products.DesignProduct', verbose_name='Дизайн-продукт')),
            ],
            options={
                'verbose_name_plural': 'изображения к дизайну',
                'verbose_name': 'изображение к дизайну',
            },
        ),
    ]
